### ISSUE TITLE
R cannot find scala dependencies

### ISSUE THREAD

**Issue by yangjas** [CristinaHG/OCAPIS#5]
When trying to run OCAPIS to fit an svm I get the following message:

```
<console>:12: error: not found: value cristinahg
             import cristinahg.ocapis.svmop._
                    ^
<console>:13: error: not found: value cristinahg
             import cristinahg.ocapis.kdlor._
                    ^
<console>:14: error: not found: value cristinahg
             import cristinahg.ocapis.wknn._
                    ^
<console>:15: error: not found: value cristinahg
             import cristinahg.ocapis.MonoFSelector._
                    ^
<console>:16: error: not found: value cristinahg
             import cristinahg.ocapis.TSS._
                    ^
```

**Comment by CristinaHG** [comment]
Hi! thanks for pointing that out! 
I just updated the .jar containing the scala algorithms and for me it works fine now :)
I also updated the README.md file with further instructions about how to compile the libsvm-weights-3.17 used underneath by the SVMOP provided with OCAPIS.

Please, keep in mind that OCAPIS was build using R 3.3 and rscala 3.2.
I just tried it with R=3.3 and rscala=3.2.2  and works fine! so you wouldn't expect any problems while using these versions.

By the way, I'd love to know if you try with another version (either of R, rscala or both), so please, if you do it, let me know what happens!
